#!/bin/bash
#
#====================================================================#
#                                                                    #
# Copyright 2009 Mikael Granvik, Jenni Virtanen, Karri Muinonen,     #
#                Teemu Laakso, Dagmara Oszkiewicz                    #
#                                                                    #
# This file is part of OpenOrb.                                      #
#                                                                    #
# OpenOrb is free software: you can redistribute it and/or modify it #
# under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or  #
# (at your option) any later version.                                #
#                                                                    #
# OpenOrb is distributed in the hope that it will be useful, but     #
# WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  #
# General Public License for more details.                           #
#                                                                    #
# You should have received a copy of the GNU General Public License  #
# along with OpenOrb. If not, see <http://www.gnu.org/licenses/>.    #
#                                                                    #
#====================================================================#
#
# This is a small utility script that downloads the most recent table
# of observatory coordinates from the Minor Planet Center and
# re-formats them for OpenOrb.
#
# Author: MG
# Date:   2009-07-27

wget http://www.cfa.harvard.edu/iau/lists/ObsCodes.html 
sed -e '2d' ObsCodes.html | grep -v "<" > OBSCODE.dat
rm -f ObsCodes.html


