#!/bin/bash
#
# (Re)Generate the contents of version.h with the version given on the
# command line.  Output to stdout. Called from build/Makefile.
#

VERSION="$1"

cat <<-EOF
	!!!!! GENERATED BY $(basename $0); DO NOT EDIT !!!!!
	CHARACTER(len=100) :: VERSION = &
	  & "$VERSION"
EOF
