#!/bin/bash
#
# (Re)Generate contents of version.pyf with the version given on the command
# line. Output to stdout. Called from build/Makefile.
#

VERSION="$1"

cat <<-EOF | sed 's|\$VERSION|'"$VERSION"'|g'
	!
	! auto-generated by $(basename $0)
	!
	    usercode '''
	#if PY_VERSION_HEX >= 0x03000000
	  s = PyUnicode_FromString(
	#else
	  s = PyString_FromString(
	#endif
	  "$VERSION"
	);
	  PyDict_SetItemString(d, "__version__", s);
	    '''
	!
	!
	!
EOF
