#!/bin/bash
#
#====================================================================#
#                                                                    #
# Copyright 2002-2017                                                #
# Mikael Granvik, Jenni Virtanen, Karri Muinonen, Teemu Laakso,      #
# Dagmara Oszkiewicz, Lauri Siltala                                  #
#                                                                    #
# This file is part of OpenOrb.                                      #
#                                                                    #
# OpenOrb is free software: you can redistribute it and/or modify it #
# under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or  #
# (at your option) any later version.                                #
#                                                                    #
# OpenOrb is distributed in the hope that it will be useful, but     #
# WITHOUT ANY WARRANTY; without even the implied warranty of         #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU  #
# General Public License for more details.                           #
#                                                                    #
# You should have received a copy of the GNU General Public License  #
# along with OpenOrb. If not, see <http://www.gnu.org/licenses/>.    #
#                                                                    #
#====================================================================#
#
# This is a small utility script that downloads the BC430 asteroid 
# ephemerides.
# 
#
# Author: LS
# Date:   2018-02-05

curl -L -O -\# -C - -f http://staff.not.iac.es/~siltala/asteroid_indices.txt
curl -L -O -\# -C - -f http://staff.not.iac.es/~siltala/asteroid_masses.txt
curl -L -O -\# -C - -f http://staff.not.iac.es/~siltala/asteroid_ephemeris.txt

